WebApplicationExample2/Controllers/FilesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.IO;
using WebApplicationExample5.Helpers;
using WebApplicationExample5.Models;
using WebApplicationExample5.Services;

namespace WebApplicationExample5.Controllers
{
    public class FilesController : Controller
    {
        private readonly ILogger<MailController> _logger;
        private readonly IFileService _fileService;

        public FilesController(ILogger<MailController> logger, IFileService mailService)
        {
            _logger = logger;
            _fileService = mailService;
        }

        public IActionResult Index()
        {
            var files = _fileService.GetFileList();

            return View(new FileListModel()
            {
                Files = files
            });
        }

        public IActionResult ViewFile(string fileName)
        {
            var filePreview = _fileService.GetFilePreview(fileName);

            return View(new FilePreviewModel
            {
                FileContents = filePreview
            });
        }

        public IActionResult GetFile(string fileName)
        {
            var stream = _fileService.GetFileStream(fileName);

            if(stream != null)
            {
                return File(stream, ContentTypeHelper.GetContentType(fileName), fileName);
            }

            return NotFound();
        }

        public IActionResult SaveFile()
        {
            var model = new FileModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult SaveFile(FileModel model)
        {
            if(model.File == null)
                return View(model);

            try
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files");

                //create folder if not exist
                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);

                //get file extension
                FileInfo fileInfo = new FileInfo(model.File.FileName);
                string fileName = Path.GetFileName(model.File.FileName);

                string fileNameWithPath = Path.Combine(path, fileName);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    model.File.CopyTo(stream);
                }

                model.Message = "File upload successfully";
                model.File = null;

                return View(model);
            }
            catch(Exception ex)
            {
                _logger.LogError(ex.Message);

                ModelState.AddModelError("", ex.Message);

                return View(model);
            }

            //return RedirectToAction("Index", "Home");
        }
    }
}

WebApplicationExample2/Views/Shared/_LanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options;

@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div>
    <form asp-controller="Home"
          asp-action="SetLanguage"
          asp-route-returnUrl="@Context.Request.Path" method="post">
        <select name="culture" onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems" class="form-select-sm">
        </select>
    </form>
</div>

WebApplicationExample2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationExample2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationExample2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationExample2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@SharedLocalizer["Privacy"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="Index">@SharedLocalizer["Files"]</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <li>
                            @await Html.PartialAsync("_LanguagePartial")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationExample2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>